### ISSUE TITLE
How to paginate STAC results from MPC?

### ISSUE THREAD

**Issue by cjrd** [bair-climate-initiative/metaearth#2]
Microsoft Planetary computer limits STAC queries to 10k results. Here's an example configuration that returns a ton of results:

```
default_collection:
  outdir: data/
  datetime: 2013-04-02/2019-07-17
  aoi_file: config/aoi/aso-2013-2019-regions.json
  provider: 
    name: MPC

collections: 
  modis-10A1-061:
    assets:
      - all

system:
  dry_run: True
  query_asset_sizes: False
```
![image](https://user-images.githubusercontent.com/1455579/183119538-21096efd-52a9-499f-ab70-f5b52d69674a.png)

Is it possible to paginate these results? If not, can we at least warn the user that this clipping is happening and they should break up their downloads?
